<div class="alert alert-danger" role="alert">
<h1>Basics of Pytorch</h1>
<ul>
<li><ol  start='1'>
<li>Matrices</li>

</ol>
</li>
<li><ol start='2' >
<li>Math</li>

</ol>
</li>
<li><ol start='3' >
<li>Variable</li>


</ol>
</li>

</ul>
</div>

### Matrices
* In pytorch, matrix(array) is called tensors.
* 3 * 3 matrix = This is 3x3 tensor
* Lets look at array example with numpy that we already know.
    * We crate numpy array with np.numpy() method
    * Type(): type of the array. In this example it is numpy.
    * np.shape: shape of the array.Row x Column

In [1]:
import numpy as np

array = [[1,2,3], [4,5,6]]
first_array = np.array(array) # 2x3 array
print("Array Type: {} \n".format(type(first_array)))
print("Array Shape: {} \n".format(np.shape(first_array)))
print(first_array)

Array Type: <class 'numpy.ndarray'> 

Array Shape: (2, 3) 

[[1 2 3]
 [4 5 6]]


* Now examine how we implement tensor(pytorch array)
* import pytorch library with import torch
* We create tensor with torch.Tensor() method

In [9]:
# conda install pytorch

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\User\Anaconda3

  added / updated specs:
    - pytorch


The following packages will be downloaded:

    package                    |            build

Note: you may need to restart the kernel to use updated packages.
    ---------------------------|-----------------
    _pytorch_select-0.1        |            cpu_0           4 KB
    ca-certificates-2021.5.25  |       haa95532_1         112 KB
    libmklml-2019.0.5          |       haa95532_0        17.5 MB
    mkl_random-1.0.4           |   py37h343c172_0         287 KB
    ninja-1.10.2               |       h6d14046_1         250 KB
    pytorch-1.6.0              |cpu_py37h538a6d7_0       101.1 MB
    ------------------------------------------------------------
                                           Total:       119.2 MB

The following NEW packages will be INSTALLED:

  _pytorch_select    pkgs/main/win-64::_pytorch_select-0.1-cpu_0
  li

pytorch-1.6.0        | 101.1 MB  | ###1       |  31% 
pytorch-1.6.0        | 101.1 MB  | ###1       |  31% 
pytorch-1.6.0        | 101.1 MB  | ###1       |  32% 
pytorch-1.6.0        | 101.1 MB  | ###1       |  32% 
pytorch-1.6.0        | 101.1 MB  | ###1       |  32% 
pytorch-1.6.0        | 101.1 MB  | ###2       |  32% 
pytorch-1.6.0        | 101.1 MB  | ###2       |  32% 
pytorch-1.6.0        | 101.1 MB  | ###2       |  32% 
pytorch-1.6.0        | 101.1 MB  | ###2       |  33% 
pytorch-1.6.0        | 101.1 MB  | ###2       |  33% 
pytorch-1.6.0        | 101.1 MB  | ###2       |  33% 
pytorch-1.6.0        | 101.1 MB  | ###3       |  33% 
pytorch-1.6.0        | 101.1 MB  | ###3       |  33% 
pytorch-1.6.0        | 101.1 MB  | ###3       |  33% 
pytorch-1.6.0        | 101.1 MB  | ###3       |  34% 
pytorch-1.6.0        | 101.1 MB  | ###3       |  34% 
pytorch-1.6.0        | 101.1 MB  | ###3       |  34% 
pytorch-1.6.0        | 101.1 MB  | ###4       |  34% 
pytorch-1.6.0        | 101.1

In [2]:
import torch

tensor = torch.Tensor(array)
print("Array Type: {} \n".format(tensor.type))
print("Array Shape: {} \n".format(tensor.shape))
print(tensor)

Array Type: <built-in method type of Tensor object at 0x0000016036BC5D18> 

Array Shape: torch.Size([2, 3]) 

tensor([[1., 2., 3.],
        [4., 5., 6.]])


* Allocation
* In order to learn, compare numpy and tensor
    * np.ones() = torch.ones()
    * np.random.rand() = torch.rand()

In [3]:
# numpy ones
print("Numpy {} \n".format(np.ones((2,3))))

# pytorch
print(torch.ones((2,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]] 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
# numpy random
print("Numpy {} \n".format(np.random.rand(2,3)))

# pytorch random
print(torch.rand(2,3))

Numpy [[0.80378176 0.48175341 0.44343007]
 [0.6880808  0.21018362 0.89013802]] 

tensor([[0.4768, 0.8717, 0.9080],
        [0.5787, 0.7671, 0.8485]])


* Let's look at conversion between tensor and numpy arrays
    * torch.from_numpy(): from numpy to tensor
    * numpy(): from tensor to numpy

In [5]:
# random numpy array
array = np.random.rand(2,2)
print("{} {} \n".format(type(array), array))

# from numpy to tensor
from_numpy_to_tensor = torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor))

# from tensor to numpy
tensor = from_numpy_to_tensor
from_tensor_to_numpy = tensor.numpy()
print("{} {} \n".format(type(from_tensor_to_numpy), from_tensor_to_numpy)) 

<class 'numpy.ndarray'> [[0.38177414 0.12564272]
 [0.8164631  0.39017244]] 

tensor([[0.3818, 0.1256],
        [0.8165, 0.3902]], dtype=torch.float64)

<class 'numpy.ndarray'> [[0.38177414 0.12564272]
 [0.8164631  0.39017244]] 



### Basic Math with Pytorch
* Resize: view()
* a and b are tensor
* addition:torch.add(a,b) = a+b
* subtraction:a.sub(b) = a-b
* element wise multiplcaiton:torch.mul(a,b) = a*b
* element wise division:torch.div(a,b) = a/b
* mean:a.mean()
* standart deviation (std): a.std()

In [6]:
# create tensor
tensor = torch.ones(3,3)
print("\n", tensor)

# resize
print("{}{}\n".format(tensor.view(9).shape,tensor.view(9)))

# addition
print("Addition: {}\n".format(torch.add(tensor, tensor)))

# subtraction
print("Subtraction: {}\n".format(tensor.sub(tensor)))

# element wise multi.
print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor)))

# element wise divison
print("Element wise division: {}\n".format(torch.div(tensor,tensor)))

# mean
tensor = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor.mean()))

# standart deviation (std)
print("std: {}".format(tensor.std()))


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

Subtraction: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Element wise multiplication: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Element wise division: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Mean: 3.0
std: 1.5811388492584229


### Variables
* It accumulates gradients
* In neural network we have backpropagation where gradients are calculated.Therefore we need to handle gradients.
* Difference between variables and tensor is variable accumulates gradients.
* In order to make backward propagation we need variables

In [7]:
from torch.autograd import Variable

# define variable
var = Variable(torch.ones(3), requires_grad = True)
var

tensor([1., 1., 1.], requires_grad=True)

* Assume we have equation y = x^2
* Define x = [2,4] variable
* After calculation we find that y = [4,16] (y = x^2)
* Recap o equation is that o = (1/2)sum(y) = (1/2)sum(x^2)
* deriavative of o = x
* Result is equal to x so gradients are [2,4]
* Lets implement

In [9]:
# lets make basic backward propagation

#equation:y=x^2
array = [2,4]
tensor = torch.Tensor(array)
x = Variable(tensor, requires_grad=True)
y = x**2
print(" y = ",y)

# recap o equation o=1/2*sum(y)
o = (1/2)*sum(y)
print(" o = ",o)

# backward
o.backward() # calculates gradients

print("gradients: ",x.grad)

 y =  tensor([ 4., 16.], grad_fn=<PowBackward0>)
 o =  tensor(10., grad_fn=<MulBackward0>)
gradients:  tensor([2., 4.])
